language: rust
sudo: required
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - kcov

after_success: |
  for file in target/debug/playlist_api-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash)
