[package]
name = "tracktor"
version = "0.1.0"
authors = ["h4llow3En <development@felixdoering.com>"]

[dependencies]
actix-web = "0.6"
diesel = "1.3.2"
regex = "1.0.2"
lazy_static = "1.1.0"
failure = "0.1.2"
